### ISSUE TITLE
Help document for FLAME visualizer

### ISSUE THREAD

**Issue by FLAMEuser** [FLAME-HPC/flame_visualiser#1]
I am having some difficulties in using FLAME visualizer. any help document or tutorial available pls?

**Comment by mondus** [comment]
@FLAMEuser Can you be more specific about what the issue is that you are having? Are you having trouble building or running the visualiser? What specifically.

I don't think there are any current tutorials for the visualiser.

**Comment by FLAMEuser** [comment]
Thanks
