### ISSUE TITLE
Should I expect the visualizer to work on Ubuntu 16.04?

### ISSUE THREAD

**Issue by MarkVallevand** [FLAME-HPC/flame_visualiser#2]
I've built the on Ubuntu 16.04 and had no troubles do that.  But, when executing it, all the fields are grey.

**Comment by mozhgan-kch** [comment]
Can confirm the same behaviour on my 16.04 machine. The way around it to use `sudo`
![screenshot_2017-11-20_13-57-49](https://user-images.githubusercontent.com/22101974/33021750-db228b74-cdfa-11e7-848c-c79e8db3fe24.png)
.
`sudo ./FLAME\ Visualiser `

Then open a config file (file - open) for any of the test models.
E.g: File -> Open -> tests -> models -> orthogonal_test

**Comment by MarkVallevand** [comment]
I still get grayed out fields.  But, the menu bar now appears.

**Comment by MarkVallevand** [comment]
I needed to use the visualizer to create the config file first, then it seems to work.

**Comment by mondus** [comment]
Thanks @mozhgan-kch will close this now.
